config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users
  resources :financials
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/financial.rb
class Financial < ApplicationRecord
  belongs_to :user
  
  validates :year, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :revenues, presence: true
  validates :grossRevenues, presence: true
  validates :operateRevenues, presence: true
  validates :nonOperateRevenues, presence: true
  validates :incomeTax, presence: true
  validates :income, presence: true
  validates :expense, presence: true
  validates :currentAssets, presence: true
  validates :fixedAssets, presence: true
  validates :totalAssets, presence: true
  validates :currentLiabilites, presence: true
  validates :fixedLiabilites, presence: true
  validates :totalLiabilites, presence: true
  validates :copitalStock, presence: true
  
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :financials
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper

  private
  
    def require_user_logged_in
      unless logged_in?
        redirect_to login_url
      end
    end
end

app/controllers/financials_controller.rb
class FinancialsController < ApplicationController
  before_action :require_user_logged_in
  
  def index
    @financials = current_user.financials
  end
  
  def show
    @financial = Financial.find(params[:id])
  end
  
  def new
    @financial = current_user.financials.build
  end
  
  def create
    @financial = current_user.financials.build(finance_params)
    
    if @financial.save
      flash[:success] = '財務諸表を登録しました。'
      redirect_to financials_path
    else
      flash.now[:danger] = '全てのフォームに入力してください。'
      render :new
    end
  end
  
  def edit
    @financial = Financial.find(params[:id])
  end
  
  def update
    @financial = Financial.find(params[:id])
    if @financial.update(finance_params)
      flash[:success] = '更新されました。'
      redirect_to @financial
    else
      flash[:danger] = '全てのフォームに入力してください。'
      render :edit
    end
  end
  
  def destroy
    @financial = Financial.find(params[:id])
    @financial.destroy
    
    flash[:success] = "削除しました。"
    redirect_to financials_url
  end

  private
    def finance_params
      params.require(:financial).permit(:year,:revenues,:grossRevenues,:operateRevenues,:nonOperateRevenues,:incomeTax,:income,:expense,:currentAssets ,:fixedAssets ,:totalAssets ,:currentLiabilites ,:fixedLiabilites ,:totalLiabilites ,:copitalStock, :name)
    end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      #redirect_to @user
      redirect_to financials_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
    def login(email, password)
      @user = User.find_by(email: email)
      if @user && @user.authenticate(password)
        session[:user_id] = @user.id
        return true
      else
        return false
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
#    @users = User.all
  end

  def show
#    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザーを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/financials_helper.rb
module FinancialsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/financials/edit.html.erb
<div class="container">
  <div class="finance-wrapper">
    
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <h3 class="finance-title">財務諸表編集</h3>
        
        <%= form_with(model: @financial, local: true) do |f| %>
            
          <div class="form-group">
            <%= f.select :year, [[2020,2020],[2019, 2019],[2018,2018],[2017,2017]], class: "select" %>
          </div>
          
          <div class="form-group">
            <%= f.label :name, '企業名' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group finance-sheet">
            <h3>損益計算書</h3><p>単位：（百万円）</p>  
          </div>
          
          <div class="form-group">
            <%= f.label :revenues, '売上高' %>
            <%= f.number_field :revenues, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :grossRevenues, '売上総利益' %>
            <%= f.number_field :grossRevenues, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :operateRevenues, '営業利益' %>
            <%= f.number_field :operateRevenues, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :nonOperateRevenues, '経常利益' %>
            <%= f.number_field :nonOperateRevenues, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :incomeTax, '税引き前当期純利益' %>
            <%= f.number_field :incomeTax, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :income, '当期純利益' %>
            <%= f.number_field :income, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :expense, '販管費' %>
            <%= f.number_field :expense, class: 'form-control' %>
          </div>
          
          <div class="form-group finance-sheet">
            <h3>貸借対照表</h3><p>単位：（百万円）</p>  
          </div>
          
          
          <div class="form-group">
            <%= f.label :currentAssets, '流動資産' %>
            <%= f.number_field :currentAssets, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :fixedAssets, '固定資産' %>
            <%= f.number_field :fixedAssets, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :totalAssets, '純資産' %>
            <%= f.number_field :totalAssets, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :currentLiabilites, '流動負債' %>
            <%= f.number_field :currentLiabilites, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :fixedLiabilites, '固定負債' %>
            <%= f.number_field :fixedLiabilites, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :totalLiabilites, '負債合計' %>
            <%= f.number_field :totalLiabilites, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :copitalStock, '純資産合計' %>
            <%= f.number_field :copitalStock, class: 'form-control' %>
          </div>
          
          <div class="form-group btn-style">
            <%= f.submit '変更する', class: 'submit btn-block btn-style' %>
          </div>
          
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/financials/index.html.erb
<div class="container">
  <div class="top-wrapper">
    
    <% @financials.each do |financial| %>
      <div class="inc-group">
        <h1 class="left"><%= financial.name %></h1>
        <div class="right">
          <%= link_to '詳細', financial, class: 'financial-item btn-item' %> 
          <%= link_to '変更', edit_financial_path(financial), class: 'btn-item' %>
          <% if current_user == financial.user %>
            <%= link_to '削除', financial, method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: 'btn-item' %>
          <% end %>
        </div>
        <div class="clear"></div>
      </div>
    <% end %>
  </div>
</div>

app/views/financials/new.html.erb
<div class="container">
  <div class="finance-wrapper">
    
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <h3 class="finance-title">財務諸表作成</h3>
        
        <%= form_with(model: @financial, local: true) do |f| %>
          <div class="form-group">
            <%= f.select :year, [[2020,2020],[2019, 2019],[2018,2018],[2017,2017]], class: "select" %>
          </div>
          
          <div class="form-group">
            <%= f.label :name, '企業名' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group finance-sheet">
            <h3>損益計算書</h3><p>単位：（百万円）</p>  
          </div>
          
          <div class="form-group">
            <%= f.label :revenues, '売上高' %>
            <%= f.number_field :revenues, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :grossRevenues, '売上総利益' %>
            <%= f.number_field :grossRevenues, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :operateRevenues, '営業利益' %>
            <%= f.number_field :operateRevenues, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :nonOperateRevenues, '経常利益' %>
            <%= f.number_field :nonOperateRevenues, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :incomeTax, '税引き前当期純利益' %>
            <%= f.number_field :incomeTax, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :income, '当期純利益' %>
            <%= f.number_field :income, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :expense, '販管費' %>
            <%= f.number_field :expense, class: 'form-control' %>
          </div>
          
          <div class="form-group finance-sheet">
            <h3>貸借対照表</h3><p>単位：（百万円）</p>  
          </div>
          
          
          <div class="form-group">
            <%= f.label :currentAssets, '流動資産' %>
            <%= f.number_field :currentAssets, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :fixedAssets, '固定資産' %>
            <%= f.number_field :fixedAssets, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :totalAssets, '純資産' %>
            <%= f.number_field :totalAssets, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :currentLiabilites, '流動負債' %>
            <%= f.number_field :currentLiabilites, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :fixedLiabilites, '固定負債' %>
            <%= f.number_field :fixedLiabilites, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :totalLiabilites, '負債合計' %>
            <%= f.number_field :totalLiabilites, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :copitalStock, '純資産合計' %>
            <%= f.number_field :copitalStock, class: 'form-control' %>
          </div>
          
          <div class="form-group btn-style">
            <%= f.submit '登録する', class: 'submit btn-block btn-style' %>
          </div>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/financials/show.html.erb
<div class="container">
  <div class="finance-wrapper">
    <div class="inc-title">
      <%= @financial.name %>
    </div>
    
    <div class="inc-btn">
      <%= link_to '変更', edit_financial_path, class: 'btn-item show-btn' %>
      <% if current_user == @financial.user %>
        <%= link_to '削除', @financial, method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: 'btn-item show-btn' %>
      <% end %>
    </div>
    <div class="clear"></div>
    
    <div class="fin-data">
    <div class="pl-wrapper">
      <p class="table-title">損益計算書 <small>単位：（百万円）</small></p>
      <p>売上高         : <%= @financial.revenues %></p>
      <p>売上総利益     : <%= @financial.grossRevenues %></p>
      <p>営業利益       : <%= @financial.operateRevenues %></p>
      <p>経常利益       : <%= @financial.nonOperateRevenues %></p>
      <p>税前当期純利益 : <%= @financial.incomeTax %></p>
      <p>当期純利益     : <%= @financial.income %></p>
      <p>販管費         : <%= @financial.expense %></p>
    </div>
    
    <div class="bs-wrapper">
      <p class="table-title">貸借対照表 <small>単位：（百万円）</small></p>
      <p>流動資産  : <%= @financial.currentAssets %></p>
      <p>固定資産  : <%= @financial.fixedAssets %></p>
      <p>総資産    : <%= @financial.totalAssets %></p>
      <p>流動負債  : <%= @financial.currentLiabilites %></p>
      <p>固定負債  : <%= @financial.fixedLiabilites %></p>
      <p>負債合計  : <%= @financial.totalLiabilites %></p>
      <p>純資産合計: <%= @financial.copitalStock %></p>
    </div>
    </div>
    
    <div class="result">
    <div class="result-wrapper">
      <p class="tables-title"></p>
      
      <table border="1">
        <figcaption>経営状況</figcaption>
        <tr>
          <td class="fin-name">売上総利益率</td><td class="fin-per"><%= (@financial.grossRevenues.to_f / @financial.revenues.to_f).round(2) * 100 %></td>
        </tr>
        <tr>
          <td class="fin-name">営業利益率</td><td class="fin-per"><%= (@financial.operateRevenues.to_f / @financial.revenues.to_f).round(2) * 100 %></td>
        </tr>
        <tr>
          <td class="fin-name">経常利益率</td><td class="fin-per"><%= (@financial.nonOperateRevenues.to_f / @financial.revenues.to_f).round(2) * 100 %></td>
        </tr>
        <tr>
          <td class="fin-name">当期純利益率</td><td class="fin-per"><%= (@financial.income.to_f / @financial.revenues.to_f).round(2) * 100 %></td>
        </tr>
        <tr>
          <td class="fin-name">販管費率</td><td class="fin-per"><%= ((@financial.expense.to_f / @financial.revenues.to_f).round(2) * 100).round(2)  %></td>
        </tr>
      </table>
    </div>
    
    <div class="result-wrapper">
      
      <table border="1">
        <figcaption>会社の収益性</figcaption>
        <tr>
          <td class="fin-name">総資産利益率(ROA)</td><td class="fin-per"><%= (@financial.income.to_f / @financial.totalAssets.to_f).round(2) * 100 %></td>
        </tr>
        <tr>
          <td class="fin-name">営業利益のROA</td><td class="fin-per"><%= (@financial.operateRevenues.to_f / @financial.totalAssets.to_f).round(2) * 100 %></td>
        </tr>
        <tr>
          <td class="fin-name">自己資本利益率(ROE)</td><td class="fin-per"><%= (@financial.income.to_f / @financial.copitalStock.to_f).round(2) * 100 %></td>
        </tr>
        <tr>
          <td class="fin-name">営業利益のROE</td><td class="fin-per"><%= (@financial.operateRevenues.to_f / @financial.copitalStock.to_f).round(2) * 100 %></td>
        </tr>
        <tr>
          <td class="fin-name">総資産回転率</td><td class="fin-per"><%= (@financial.revenues.to_f / @financial.totalAssets.to_f).round(2) * 100 %></td>
        </tr>
      </table>
    </div>
    
    <div class="result-wrapper">
      
      <table border="1">
        <figcaption>会社の安全性</figcaption>
        <tr>
          <td class="fin-name">自己資本比率</td><td class="fin-per"><%= (@financial.copitalStock.to_f / @financial.totalAssets.to_f).round(2) * 100 %></td>
        </tr>
        <tr>
          <td class="fin-name">流動比率</td><td class="fin-per"><%= (@financial.currentAssets.to_f / @financial.currentLiabilites.to_f).round(2) * 100 %></td>
        </tr>
        <tr>
          <td class="fin-name">固定比率</td><td class="fin-per"><%= (@financial.fixedAssets.to_f / @financial.copitalStock.to_f).round(2) * 100 %></td>
        </tr>
        <tr>
          <td class="fin-name">固定長期適合率</td><td class="fin-per"><%= (@financial.fixedAssets.to_f / (@financial.copitalStock.to_f + @financial.fixedLiabilites.to_f)).round(2) * 100 %></td>
        </tr>
      </table>
    </div>
    </div>
    <div class="clear"></div>
    
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<div class="container">
  <div class="flash-wrapper">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<header>
  <div class="container">
    <div class="header-left">
      <p class="logo">Stack Calc</p>
    </div>
    <div class="header-right">
      <% if logged_in? %>
        <div class="signup" id="signup-show"><%= link_to '企業リスト', financials_path, class: 'signup' %></div>
        <div class="login" id="login-show"><%= link_to '財務登録', new_financial_path, class: 'signup' %></div>
        <div class="login" id="login-show"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'signup' %></div>
      <% else %>
        <div class="signup" id="signup-show"><%= link_to 'サインアップ', signup_path, class: 'signup' %></div>
        <div class="login" id="login-show"><%= link_to 'ログイン', login_path, class: 'signup' %></div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Stack Calc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_messages' %>
    
    <%= yield %>
  </body>
</html>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <div class="signup_login_form">
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @user, local: true) do |f| %>
          <div class="form-group">
            <%= f.label :name, '名前' %>
            <%= f.text_field :name, class:'form-control' %>
          </div>
              
          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
              
          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
              
          <div class="form-group">
            <%= f.label :password_confirmation, '確認用パスワード' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
              
          <div class="sign-btn">
            <%= f.submit 'サインアップ', class: 'submit btn-block' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
    